linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 14
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  gocritic:
    settings:
      rangeValCopy:
        sizeThreshold: 1024
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - paramTypeCombine
      - hugeParam
      - commentedOutCode
  funlen:
    lines: 110
    statements: 50

linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - gofumpt
    - maligned
    - prealloc
    - gochecknoglobals
    - scopelint
    - lll
    - dupl
    - goconst
    - unparam
    - whitespace
    - godox
    - gomnd
    - testpackage
    - paralleltest
    - goerr113
    - wrapcheck
    - noctx

run:
  skip-dirs:
    - node_modules
    - mocks
    - integration
    - migrations

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gochecknoinits
        - gocritic
        - golint
        - bodyclose
        - funlen
        - stylecheck
        - interfacer
