### Note: commented out options are prefixed "#", explanations are prefixed with "###"
### Optional configuration options are set to their default value.
###
### The S3 bucket used for credential exchange
s3bucket:
  ### The name of the bucket used for exchanging credentials. you may name it whatever you want.
  ### Note that S3 has a global bucket namespace, so your name needs to be globally unique.
  bucket-name: example-credentials-exchange
  ### This is the role to be assumed from the developer's workstation to access the S3 bucket
  role-arn: arn:aws:iam::000000000000:role/devops-engineer
  ### Optional: This is the role to be assumed from the CI workflow to access the S3 bucket.
  ### If you don't provide this, the bucket will be accessed without assuming a role
  # await-role-arn: arn:aws:iam::123456789:role/ci-workflow
### This list contains an element for every stage of deployment in the CI workflow
stages:
  - name: dev
    role-arn: arn:aws:iam::111111111111:role/devops-engineer
  - name: int
    role-arn: arn:aws:iam::222222222222:role/devops-engineer

### by default we enforce that stage-credentials are used in the right order and just once
### This may bot be appropriate in all cases, e.g. when you want to do something in DEV after performing the PRD deployment
# enforce-order: true
### This is where credentials are persisted to.
### If you want to use per-stage container instances, pass it on in the CI system as a workflow artifact.
# credentials-path: ./secret-inject-cred-set.yaml
### The lifetime of the short-term credentials injected into the pipeline
# credentials-duration-seconds: 1200
### Whether the tool should comment on PR. This is most conventient in GitHub actions.
### See https://docs.github.com/en/actions/reference/authentication-in-a-workflow#using-the-github_token-in-a-workflow
### On how to inject the token into your workflow.
# comment-on-pr: true
